DROP TABLE vote IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE user IF EXISTS;
DROP TABLE restaurant IF EXISTS;

create table restaurant
(
id int generated by default as identity (start with 1 increment by 1) primary key ,
name varchar(255) not null
);

create table menu
(
id int generated by default as identity (start with 1 increment by 1) primary key ,
name varchar(255) not null,
price int not null,
datemenu timestamp default now not null,
id_rest int, foreign key (id_rest) references restaurant(id) on delete cascade
);

create table user
(
id int generated by default as identity (start with 1 increment by 1) primary key ,
name varchar(255) not null,
email varchar(255) not null,
password varchar(255) not null,
role varchar(255) not null
);
create unique index user_unique_email_idx
on user (email);

create table vote
(
id int generated by default as identity (start with 1 increment by 1) primary key ,
dateVote date not null,
id_rest  int not null,
id_user  int not null,
foreign key (id_rest) references restaurant (id) on delete cascade,
foreign key (id_user) references user (id) on delete cascade
);

create unique index user_unique_dateVote_idx
on vote (id_user, dateVote);

